services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/app/db

  backend:
    build:
      context: ./source/back-end
      dockerfile: Dockerfile
    container_name: rag-backend
    ports:
      - "8080:8080"
    environment:
      - WATSONX_URL=${WATSONX_URL}
      - WATSONX_PROJECT_ID=${WATSONX_PROJECT_ID}
      - WATSONX_APIKEY=${WATSONX_APIKEY}
      - CHROMA_HOST=http://chroma:8000
    depends_on:
      - chroma
    volumes:
      - ./assets:/assets
  
  frontend:
    build:
      context: ./source/front-end
      dockerfile: Dockerfile
    container_name: rag-frontend
    ports:
      - "8501:8501"     
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend
